/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\gltfsforreact.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

const HELIX_SPEED = 6;

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/models/gltfsforreact.glb')

  const helix = useRef();

  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED;
  })

  return (
    <group {...props} dispose={null}>
        <mesh geometry={nodes.Plane.geometry} material={materials.plane} rotation={[Math.PI / 2, 0, 0]} />
        <mesh ref={helix} geometry={nodes.Helix.geometry} material={materials.plane} rotation={[Math.PI / 3, 0, 0]} position = {[0,0,.1]} />
    </group>
  )
}

useGLTF.preload('/models/gltfsforreact.glb');
